import streamlit as st
from pathlib import Path

st.set_page_config(layout="wide")


col1, col2, col3 = st.columns(3)
col2.markdown("""
              # World Cup 2022 Predictor

The model developed using the machine learning tries to predict the results of world cup matches. The model, which was originally developed to predict only the teams that get through to the last 16 rounds, can also make predictions in the group stages. The model produces a result on the odds of both sides winning. If these odds are close, it recommends playing a double chance. In the round of 16, it will only guess the team that get through to the next round.

The theoretical success rate of the model is 69%. At the end of the tournament, achieving this rate will make the model as successful.

The page will be updated daily.

              """)


col1, col2, col3, col4, col5, col6 = st.columns(6)

successed_matches = 17.0
total_matches = 24.0
col3.metric("Predicted Number Of Matches", value=int(total_matches))
succes_rate_str = str(int(successed_matches/total_matches*100))+'%'
succes_rate = str(int(successed_matches)) + "/" + str(int(total_matches))
col4.metric("Success Rate", value=succes_rate_str, delta=succes_rate)


import pandas as pd
import numpy as np
d = {'Team 1': ["Qatar",
                "England",
                "Senegal",
                "USA",
                "Argentina",
                "Denmark",
                "Mexico",
                "France",
                "Morocco",
                "Germany",
                "Spain",
                "Belgium",
                "Switzerland",
                "Uruguay",
                "Portugal",
                "Brazil",
                "Wales",
                "Qatar",
                "Holland",
                "England",
                "Tunisia",
                "Poland",
                "France",
                "Argentina",
                "Japan",
                "Belgium",
                "Croatia",
                "Spain",
                "Cameroon",
                "South Korea",
                "Brazil",
                "Portugal",
                "Ecuador",
                "Holland",
                "Iran",
                "Wales",
                "Australia",
                "Tunisia",
                "Saudi Arabia",
                "Poland",
                "Croatia",
                "Canada",
                "Costa Rica",
                "Japan",
                "Ghana",
                "South Korea",
                "Cameroon",
                "Serbia"
                ], 
     'Team 2': ["Ecuador",
                "Iran",
                "Holland",
                "Wales",
                "Saudi Arabia",
                "Tunisia",
                "Poland",
                "Australia",
                "Croatia",
                "Japan",
                "Costa Rica",
                "Canada",
                "Cameroon",
                "South Korea",
                "Ghana",
                "Serbia",
                "Iran",
                "Senegal",
                "Ecuador",
                "USA",
                "Australia",
                "Saudi Arabia",
                "Denmark",
                "Mexico",
                "Costa Rica",
                "Morocco",
                "Canada",
                "Germany",
                "Serbia",
                "Ghana",
                "Switzerland",
                "Uruguay",
                "Senegal",
                "Qatar",
                "USA",
                "England",
                "Denmark",
                "France",
                "Mexico",
                "Argentina",
                "Belgium",
                "Morocco",
                "Germany",
                "Spain",
                "Uruguay",
                "Portugal",
                "Brazil",
                "Switzerland"
                ],
     'Prediction': ["X2",
                    "1",
                    "2",
                    "1X",
                    "1",
                    "1",
                    "1X",
                    "1",
                    "X2",
                    "1",
                    "1",
                    "1",
                    "1",
                    "1",
                    "1",
                    "1",
                    "1",
                    "2",
                    "1",
                    "1",
                    "2X",
                    "1",
                    "1",
                    "1",
                    "1",
                    "1",
                    "1",
                    "1X",
                    "2",
                    "1",
                    "1",
                    "1",
                    "2",
                    "1",
                    "X2",
                    "2",
                    "2",
                    "2",
                    "2",
                    "2",
                    "X2",
                    "X2",
                    "2",
                    "2",
                    "2",
                    "2",
                    "2",
                    "X2"
                    ],
     'Odd': ["1.35",
             "1.35",
             "1.62",
             "1.40",
             "1.18",
             "1.47",
             "1.45",
             "1.24",
             "1.21",
             "1.52",
             "1.17",
             "1.47",
             "1.72",
             "1.82",
             "1.45",
             "1.46",
             "2.20",
             "1.65",
             "1.74",
             "1.57",
             "1.74",
             "1.77",
             "1.80",
             "1.60",
             "1.48",
             "2.04",
             "2.15",
             "1.43",
             "1.74",
             "2.65",
             "1.40",
             "1.95",
             "2.75",
             "1.18",
             "1.23",
             "1.57",
             "1.46",
             "1.35",
             "1.70",
             "1.52",
             "1.38",
             "1.45",
             "1.11",
             "1.30",
             "1.85",
             "1.62",
             "1.23",
             "1.60"],
             
     'Success': ["✅",
                 "✅",
                 "✅",
                 "✅",
                 "❌",
                 "❌",
                 "✅",
                 "✅",
                 "✅",
                 "❌",
                 "✅",
                 "✅",
                 "✅",
                 "❌",
                 "✅",
                 "✅",
                 "❌",
                 "✅",
                 "❌",
                 "❌",
                 "✅",
                 "✅",
                 "✅",
                 "✅",
                 "-",
                 "-",
                 "-",
                 "-",
                 "-",
                 "-",
                 "-",
                 "-",
                 "-",
                 "-",
                 "-",
                 "-",
                 "-",
                 "-",
                 "-",
                 "-",
                 "-",
                 "-",
                 "-",
                 "-",
                 "-",
                 "-",
                 "-",
                 "-",

                 ]}
df = pd.DataFrame(data=d)
df.index = np.arange(1, len(df) + 1)

# Function 
def color_df(val):
    if val == "✅":
        color = 'green'
    else :
        color = 'red'
    return f'background-color: {color}'

col1, col2, col3 = st.columns(3)

col2.dataframe(df.style.applymap(color_df, subset=['Success']),
                  600, 1800)


# streamlit run /Users/berkanyuce/Documents/GitHub/World-Cup-2022/main.py

